# Generated by Django 3.2.9 on 2022-03-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_auth_auth_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='auth_number',
            field=models.IntegerField(null=True, verbose_name='인증 번호'),
        ),
    ]
